// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.1
// source: proto/dealership/dealership.proto

package dealership

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// DealershipServiceClient is the client API for DealershipService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DealershipServiceClient interface {
}

type dealershipServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDealershipServiceClient(cc grpc.ClientConnInterface) DealershipServiceClient {
	return &dealershipServiceClient{cc}
}

// DealershipServiceServer is the server API for DealershipService service.
// All implementations must embed UnimplementedDealershipServiceServer
// for forward compatibility.
type DealershipServiceServer interface {
	mustEmbedUnimplementedDealershipServiceServer()
}

// UnimplementedDealershipServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDealershipServiceServer struct{}

func (UnimplementedDealershipServiceServer) mustEmbedUnimplementedDealershipServiceServer() {}
func (UnimplementedDealershipServiceServer) testEmbeddedByValue()                           {}

// UnsafeDealershipServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DealershipServiceServer will
// result in compilation errors.
type UnsafeDealershipServiceServer interface {
	mustEmbedUnimplementedDealershipServiceServer()
}

func RegisterDealershipServiceServer(s grpc.ServiceRegistrar, srv DealershipServiceServer) {
	// If the following call pancis, it indicates UnimplementedDealershipServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DealershipService_ServiceDesc, srv)
}

// DealershipService_ServiceDesc is the grpc.ServiceDesc for DealershipService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DealershipService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dealership.DealershipService",
	HandlerType: (*DealershipServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "proto/dealership/dealership.proto",
}
